### ISSUE TITLE
protobuf not working on mac 10.9 from python

### ISSUE THREAD

**Issue by barakr** [salilab/npctransport#18]
Hi Ben, on Mac 10.9 (and Windows only) - tests that use protobuf through python are unhappy, see example below. Do you have any hunch about what should cause this / would fix this? Probably something in the interface between swig and protobuf?
Barak
# test_protobufs.py
## ERROR: ConeTests.test_1

Traceback (most recent call last):
  File "/tmp/nightly-build-55647/imp-20140502.develop.1442869/modules/npctransport/test/test_protobufs.py", line 47, in test_1
    self._make_config(config_name)
  File "/tmp/nightly-build-55647/imp-20140502.develop.1442869/modules/npctransport/test/test_protobufs.py", line 11, in _make_config
    config= IMP.npctransport.Configuration()
AttributeError: 'module' object has no attribute 'Configuration'
